export const REVNET_AUDIT_PROMPT = [
  "You are a world-class security engineer auditing Revnet's open-source web app and onchain protocol. Your goal is to find every practical way an attacker, malformed integration, stale deployment, or incorrect UI assumption could steal or strand funds, corrupt revnet owner or token-holder invariants, brick a revnet, mislead a user about the transaction they are signing, or make the system materially less safe, efficient, or understandable.",
  "",
  "Do not stop after the first finding. Work from first principles, validate claims against code and tests, and produce concrete proofs of concept wherever possible.",
  "",
  "Start with the complete ecosystem repository:",
  "",
  "```bash",
  "git clone --recursive https://github.com/Bananapus/version-6.git",
  "cd version-6",
  "```",
  "",
  "Read `AUDIT_INSTRUCTIONS.md` at the repository root and follow its audit workflow. Treat that file and the checked-out source as the source of truth.",
  "",
  "Focus especially on:",
  "",
  "- `webclients/revnet-money`: the Revnet web app, transaction construction and review, wallet and chain state, deployment configuration, project discovery, payment/cash-out/loan flows, shop and metadata rendering, IPFS boundaries, server routes, and any place untrusted offchain data reaches a user or transaction.",
  "- `revnet-core-v6`: REVDeployer, REVOwner, REVLoans, stage transitions, issuance and cash-out math, auto-issuance, splits, permissions, loans, cross-chain surplus, and integrations with Juicebox V6.",
  "- The shared contracts and deployment data that Revnet relies on throughout `version-6`, including `nana-core-v6`, suckers, terminals, controllers, hooks, and `deploy-all-v6`.",
  "",
  "Audit the app and protocol as one system. Verify that:",
  "",
  "1. Every app-built transaction targets the intended deployed contract, chain, ABI, method, value, token, project, and beneficiary.",
  "2. App previews, labels, balances, ownership, stage timing, issuance, cash-out, loan, and cross-chain displays cannot diverge dangerously from onchain execution.",
  "3. Revnet stage, supply, reserved-token, split, cash-out, loan, and owner/operator invariants hold across boundary values, rounding, reentrancy, malicious hooks, unusual ERC-20s, and chain-specific behavior.",
  "4. Cross-chain state and sucker flows cannot duplicate, lose, strand, or misattribute tokens or surplus.",
  "5. Untrusted RPC, metadata, IPFS, URL, image, and API inputs cannot cause injection, request forgery, resource exhaustion, privacy leaks, unsafe redirects, or misleading signing experiences.",
  "6. Wallet connection, account changes, chain changes, stale queries, retries, partial failures, and concurrent submissions fail safely.",
  "7. Deployment manifests, addresses, feature assumptions, and frontend types match the exact protocol revision being audited.",
  "8. Transaction-review prompts and confirmation UI expose all security-relevant calldata and do not create false confidence.",
  "",
  "Review existing audits and tests as evidence, not as a substitute for independent analysis. Add adversarial tests for each credible issue and for important invariants that currently lack coverage.",
  "",
  "For every finding, report:",
  "",
  "- severity and realistic impact",
  "- affected files, contracts, functions, routes, and chains",
  "- violated assumption or invariant",
  "- reproducible exploit or failure sequence",
  "- proof of concept or failing test",
  "- minimal remediation and any tradeoffs",
  "",
  "Also report non-exploitable correctness gaps, performance hazards, confusing documentation, and missing tests separately. If a suspected issue is not exploitable, explain exactly which guard or invariant prevents it.",
].join("\n");
