FROM node:22.16.0-bookworm-slim@sha256:048ed02c5fd52e86fda6fbd2f6a76cf0d4492fd6c6fee9e2c463ed5108da0e34 AS base

ENV NEXT_TELEMETRY_DISABLED=1
WORKDIR /app

FROM base AS dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts --no-audit --no-fund

FROM base AS builder
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_BENDYSTRAW_URL
ARG NEXT_PUBLIC_TESTNET_BENDYSTRAW_URL
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ARG NEXT_PUBLIC_INFURA_IPFS_HOSTNAME
ARG NEXT_PUBLIC_MAINNET_SUBGRAPH_URL
ARG NEXT_PUBLIC_OPTIMISM_SUBGRAPH_URL
ARG NEXT_PUBLIC_BASE_SUBGRAPH_URL
ARG NEXT_PUBLIC_ARBITRUM_SUBGRAPH_URL
ARG NEXT_PUBLIC_SEPOLIA_SUBGRAPH_URL
ARG NEXT_PUBLIC_OPTIMISM_SEPOLIA_SUBGRAPH_URL
ARG NEXT_PUBLIC_BASE_SEPOLIA_SUBGRAPH_URL
ARG NEXT_PUBLIC_ARBITRUM_SEPOLIA_SUBGRAPH_URL
ARG NEXT_PUBLIC_RPC_ETHEREUM_URLS
ARG NEXT_PUBLIC_RPC_OPTIMISM_URLS
ARG NEXT_PUBLIC_RPC_BASE_URLS
ARG NEXT_PUBLIC_RPC_ARBITRUM_URLS
ARG NEXT_PUBLIC_RPC_ETHEREUM_SEPOLIA_URLS
ARG NEXT_PUBLIC_RPC_OPTIMISM_SEPOLIA_URLS
ARG NEXT_PUBLIC_RPC_BASE_SEPOLIA_URLS
ARG NEXT_PUBLIC_RPC_ARBITRUM_SEPOLIA_URLS

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_BENDYSTRAW_URL=$NEXT_PUBLIC_BENDYSTRAW_URL \
    NEXT_PUBLIC_TESTNET_BENDYSTRAW_URL=$NEXT_PUBLIC_TESTNET_BENDYSTRAW_URL \
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID \
    NEXT_PUBLIC_INFURA_IPFS_HOSTNAME=$NEXT_PUBLIC_INFURA_IPFS_HOSTNAME \
    NEXT_PUBLIC_MAINNET_SUBGRAPH_URL=$NEXT_PUBLIC_MAINNET_SUBGRAPH_URL \
    NEXT_PUBLIC_OPTIMISM_SUBGRAPH_URL=$NEXT_PUBLIC_OPTIMISM_SUBGRAPH_URL \
    NEXT_PUBLIC_BASE_SUBGRAPH_URL=$NEXT_PUBLIC_BASE_SUBGRAPH_URL \
    NEXT_PUBLIC_ARBITRUM_SUBGRAPH_URL=$NEXT_PUBLIC_ARBITRUM_SUBGRAPH_URL \
    NEXT_PUBLIC_SEPOLIA_SUBGRAPH_URL=$NEXT_PUBLIC_SEPOLIA_SUBGRAPH_URL \
    NEXT_PUBLIC_OPTIMISM_SEPOLIA_SUBGRAPH_URL=$NEXT_PUBLIC_OPTIMISM_SEPOLIA_SUBGRAPH_URL \
    NEXT_PUBLIC_BASE_SEPOLIA_SUBGRAPH_URL=$NEXT_PUBLIC_BASE_SEPOLIA_SUBGRAPH_URL \
    NEXT_PUBLIC_ARBITRUM_SEPOLIA_SUBGRAPH_URL=$NEXT_PUBLIC_ARBITRUM_SEPOLIA_SUBGRAPH_URL \
    NEXT_PUBLIC_RPC_ETHEREUM_URLS=$NEXT_PUBLIC_RPC_ETHEREUM_URLS \
    NEXT_PUBLIC_RPC_OPTIMISM_URLS=$NEXT_PUBLIC_RPC_OPTIMISM_URLS \
    NEXT_PUBLIC_RPC_BASE_URLS=$NEXT_PUBLIC_RPC_BASE_URLS \
    NEXT_PUBLIC_RPC_ARBITRUM_URLS=$NEXT_PUBLIC_RPC_ARBITRUM_URLS \
    NEXT_PUBLIC_RPC_ETHEREUM_SEPOLIA_URLS=$NEXT_PUBLIC_RPC_ETHEREUM_SEPOLIA_URLS \
    NEXT_PUBLIC_RPC_OPTIMISM_SEPOLIA_URLS=$NEXT_PUBLIC_RPC_OPTIMISM_SEPOLIA_URLS \
    NEXT_PUBLIC_RPC_BASE_SEPOLIA_URLS=$NEXT_PUBLIC_RPC_BASE_SEPOLIA_URLS \
    NEXT_PUBLIC_RPC_ARBITRUM_SEPOLIA_URLS=$NEXT_PUBLIC_RPC_ARBITRUM_SEPOLIA_URLS

RUN npm run build

FROM base AS runner
ENV NODE_ENV=production \
    HOSTNAME=0.0.0.0 \
    PORT=3000

RUN groupadd --system --gid 1001 nodejs \
    && useradd --system --uid 1001 --gid nodejs --home-dir /app nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/scripts/validate-env.mjs ./scripts/validate-env.mjs

USER nextjs
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD ["node", "-e", "fetch('http://127.0.0.1:'+(process.env.PORT||3000)+'/api/healthz').then(r=>{if(!r.ok)throw new Error(String(r.status))}).catch(()=>process.exit(1))"]

CMD ["sh", "-c", "node scripts/validate-env.mjs runtime && exec node server.js"]
